In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.utils import to_categorical

In [2]:
file=r'C:\Users\ARUNA\Deep Learning Edvancer/Download Data/action_log.csv'

In [3]:
seq_data=pd.read_csv(file)

In [4]:
seq_data.head()

action_sequence last_action_logged
0   GCBHBEECBFDBD                  C
1   HBFDAAFDGCHAG                  G
2         FCDHHDE                  C
3        EDFHEGDD                  C
4         HFHBBBB                  C

In [5]:
max([len(t) for t in seq_data['action_sequence']])

14

In [6]:
X = seq_data['action_sequence']
Y = seq_data['last_action_logged']

In [7]:
Y

0         C
1         G
2         C
3         C
4         C
         ..
299995    G
299996    G
299997    C
299998    G
299999    C
Name: last_action_logged, Length: 300000, dtype: object

In [8]:
le=LabelEncoder()

In [9]:
le.fit_transform(Y)

array([2, 6, 2, ..., 2, 6, 2])

In [10]:
Y=to_categorical(le.fit_transform(Y))

In [11]:
Y

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [18]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15)

In [19]:
max_len = 14
tok = Tokenizer(char_level=True,split='')
tok.fit_on_texts(X_train)
sequences = tok.texts_to_sequences(X_train)

In [20]:
X_train

216033          CAEBGFC
19181        CBCHCDCFCF
52289      FHBAAGFBBHCB
259420    FAGHABEFHGCEG
187437          ECFFBGH
              ...      
218293      AAHBDDFHACB
181756      AAHEACDGBDH
231015             DACC
105686      DCDGFDADGFB
234093          GDBBBFD
Name: action_sequence, Length: 255000, dtype: object

In [21]:
sequences

[[3, 7, 1, 8, 2, 5, 3],
 [3, 8, 3, 6, 3, 4, 3, 5, 3, 5],
 [5, 6, 8, 7, 7, 2, 5, 8, 8, 6, 3, 8],
 [5, 7, 2, 6, 7, 8, 1, 5, 6, 2, 3, 1, 2],
 [1, 3, 5, 5, 8, 2, 6],
 [1, 1, 4, 3, 5, 6, 3, 5, 5, 6, 4, 8, 6],
 [3, 3, 7, 3, 1, 3],
 [6, 7, 4, 4, 5, 2, 7, 1, 4, 4],
 [2, 7, 7, 8, 6, 7, 1, 1, 1],
 [3, 7, 6, 4, 7],
 [4, 5, 1, 1, 8, 4, 4, 7, 3, 4, 1, 3, 3, 8],
 [7, 7, 8, 7, 6, 7, 1, 1, 5],
 [7, 6, 4],
 [7, 7, 4, 8, 4, 2, 6, 1, 3],
 [2, 7, 7, 1, 6, 5],
 [4, 1, 5],
 [3, 7, 7, 4, 3, 7, 1, 2, 6, 7, 5],
 [8, 2, 1, 5, 7, 4, 1],
 [7, 6, 6, 7, 8, 4, 7, 7, 7, 2, 5, 1, 2, 8],
 [4, 1, 7],
 [8, 4, 8, 7, 6, 4, 5],
 [1, 4, 2, 3, 3, 7, 7, 7, 5, 6, 5],
 [2, 6, 8, 8, 4, 1],
 [4, 5, 4, 1, 3, 7, 4, 3, 5],
 [5, 8, 8, 3, 7, 5, 6, 6, 3, 8, 1],
 [3, 2, 5, 3, 3, 8, 1, 4, 1, 3],
 [4, 6, 5, 5, 2, 7, 5, 4, 4, 4, 3, 4],
 [2, 8, 4, 3, 8, 3, 1],
 [6, 3, 5],
 [5, 5, 4, 2, 4, 8, 1, 5, 5, 7, 4, 1, 1],
 [2, 3, 6, 1, 1, 6],
 [2, 6, 1, 6, 6, 5, 5, 7, 1, 7, 8, 1, 8, 7],
 [5, 2, 7, 7, 7, 3, 2, 3, 1, 7, 2, 5, 8],
 [5, 4, 4, 5, 8, 1, 5,

In [22]:

tok.index_word

{1: 'e', 2: 'g', 3: 'c', 4: 'd', 5: 'f', 6: 'h', 7: 'a', 8: 'b'}

In [23]:
sequences_matrix_train = sequence.pad_sequences(sequences,maxlen=max_len)

In [24]:
sequences_matrix_train

array([[0, 0, 0, ..., 2, 5, 3],
       [0, 0, 0, ..., 5, 3, 5],
       [0, 0, 5, ..., 6, 3, 8],
       ...,
       [0, 0, 0, ..., 7, 3, 3],
       [0, 0, 0, ..., 2, 5, 8],
       [0, 0, 0, ..., 8, 5, 4]])

In [25]:
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(9,9,input_length=14,mask_zero=True)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(8,name='out_layer')(layer)
    layer = Activation('softmax')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [26]:
model = RNN()
model.summary()
model.compile(loss='categorical_crossentropy',optimizer='adam',
              metrics=['accuracy'])

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 14)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 14, 9)             81        
_________________________________________________________________
lstm (LSTM)                  (None, 64)                18944     
_________________________________________________________________
FC1 (Dense)                  (None, 256)               16640     
_________________________________________________________________
activation (Activation)      (None, 256)               0         
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
out_layer (Dense)            (None, 8)                 2056  

In [27]:
test_sequences = tok.texts_to_sequences(X_test)
test_sequences_matrix = sequence.pad_sequences(test_sequences,
                                               maxlen=max_len)

In [28]:
model.fit(sequences_matrix_train,Y_train,batch_size=10000,epochs=5,
          validation_data=(test_sequences_matrix,Y_test))

Train on 255000 samples, validate on 45000 samples
Epoch 1/5
255000/255000 [==============================] - 49s 192us/sample - loss: 1.7333 - accuracy: 0.5683 - val_loss: 1.2578 - val_accuracy: 0.5873
Epoch 2/5
255000/255000 [==============================] - 29s 115us/sample - loss: 1.1907 - accuracy: 0.5834 - val_loss: 1.1289 - val_accuracy: 0.5873
Epoch 3/5
255000/255000 [==============================] - 29s 116us/sample - loss: 1.1352 - accuracy: 0.5843 - val_loss: 1.0994 - val_accuracy: 0.5873
Epoch 4/5
255000/255000 [==============================] - 29s 113us/sample - loss: 1.1032 - accuracy: 0.5859 - val_loss: 1.0569 - val_accuracy: 0.5920
Epoch 5/5
255000/255000 [==============================] - 29s 113us/sample - loss: 1.0242 - accuracy: 0.6403 - val_loss: 0.9107 - val_accuracy: 0.7121


In [29]:
predictions=model.predict(test_sequences_matrix)

In [30]:
predictions

array([[1.29812658e-02, 1.89528428e-03, 1.56555593e-01, ...,
        5.68451174e-02, 7.17222273e-01, 3.76855843e-02],
       [1.31125040e-02, 2.02256814e-03, 2.01141253e-01, ...,
        6.08630665e-02, 6.63531363e-01, 4.19929549e-02],
       [3.05828433e-02, 1.82625670e-02, 3.70415509e-01, ...,
        1.59534663e-01, 2.01726481e-01, 1.67923838e-01],
       ...,
       [1.01327226e-02, 9.05735185e-04, 6.94965422e-02, ...,
        2.78344769e-02, 8.64422321e-01, 1.50427865e-02],
       [7.10762991e-03, 3.21506057e-04, 1.60787534e-02, ...,
        9.34467372e-03, 9.56196785e-01, 3.64706060e-03],
       [1.07215606e-02, 1.82271469e-03, 3.73377681e-01, ...,
        6.41375929e-02, 4.87292796e-01, 4.76696417e-02]], dtype=float32)

In [31]:
from sklearn.metrics import roc_auc_score

In [32]:
roc_auc_score(Y_test,predictions)

0.6679144894939173

In [33]:
# although looking at auc score ( average across all classes ) is not the best performance measure 
# classification report gives a much better idea 

In [34]:
from sklearn.metrics import classification_report

In [35]:
Y_test_pred=np.argmax(predictions,1)

In [36]:
print(classification_report(np.argmax(Y_test,1),Y_test_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       486
           1       0.00      0.00      0.00       188
           2       0.59      0.80      0.68      9821
           3       0.00      0.00      0.00       382
           4       0.00      0.00      0.00       309
           5       0.00      0.00      0.00      3923
           6       0.76      0.91      0.83     26430
           7       0.00      0.00      0.00      3461

    accuracy                           0.71     45000
   macro avg       0.17      0.21      0.19     45000
weighted avg       0.58      0.71      0.64     45000



In [37]:
le.transform(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [38]:
# As you can see that the model is actually only making prediciton for just two majority classes