In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['boy is good',
     'girl is cute',
     'am drining apple juice',
     'he doesnot like pineapple juice',
     'i like cricket',
     'weather is sunny today',
     'i love python programming']


In [5]:
voc_size=10000

In [6]:
onehot_repr=[one_hot(word,voc_size) for word in sent]

In [7]:
onehot_repr

[[7819, 4850, 285],
 [4133, 4850, 9028],
 [8737, 2498, 513, 3496],
 [423, 2409, 5725, 5723, 3496],
 [294, 5725, 5002],
 [7543, 4850, 8570, 2027],
 [294, 294, 2621, 2728]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
import numpy as np

In [10]:
sent_len=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0    0 7819 4850  285]
 [   0    0    0    0    0 4133 4850 9028]
 [   0    0    0    0 8737 2498  513 3496]
 [   0    0    0  423 2409 5725 5723 3496]
 [   0    0    0    0    0  294 5725 5002]
 [   0    0    0    0 7543 4850 8570 2027]
 [   0    0    0    0  294  294 2621 2728]]


In [13]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
predict_embedded=model.predict(embedded_docs)

In [18]:
predict_embedded[0]

array([[ 0.04608622,  0.0270779 ,  0.00929072, -0.02918563, -0.03271638,
         0.02348052, -0.01207517,  0.0232576 ,  0.03222544,  0.00614814],
       [ 0.04608622,  0.0270779 ,  0.00929072, -0.02918563, -0.03271638,
         0.02348052, -0.01207517,  0.0232576 ,  0.03222544,  0.00614814],
       [ 0.04608622,  0.0270779 ,  0.00929072, -0.02918563, -0.03271638,
         0.02348052, -0.01207517,  0.0232576 ,  0.03222544,  0.00614814],
       [ 0.04608622,  0.0270779 ,  0.00929072, -0.02918563, -0.03271638,
         0.02348052, -0.01207517,  0.0232576 ,  0.03222544,  0.00614814],
       [ 0.04608622,  0.0270779 ,  0.00929072, -0.02918563, -0.03271638,
         0.02348052, -0.01207517,  0.0232576 ,  0.03222544,  0.00614814],
       [-0.04059788, -0.02547761, -0.03995531, -0.01044202, -0.0299605 ,
         0.01847365,  0.04583697, -0.00038289, -0.01576646, -0.01224796],
       [ 0.03566507,  0.00017918, -0.02822213,  0.04175181, -0.01040394,
         0.03703548,  0.00215092, -0.03066646